# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ha-grocy-openproject"
BBFILE_PATTERN_meta-ha-grocy-openproject = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ha-grocy-openproject = "7"

LAYERDEPENDS_meta-ha-grocy-openproject = "core"
LAYERSERIES_COMPAT_meta-ha-grocy-openproject = "kirkstone scarthgap nanbield"
